# This .travis.yml is modified from the sample at
# https://docs.haskellstack.org/en/stable/GUIDE/#travis-with-caching

# Use new container infrastructure to enable caching
sudo: false

# Do not choose a language; we provide our own build tools.
language: generic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack

# The different configurations we want to test. We have BUILD=cabal which uses
# cabal-install, and BUILD=stack which uses Stack. More documentation on each
# of those below.
#
# We set the compiler values here to tell Travis to use a different
# cache file per set of arguments.
#
# If you need to have different apt packages for each combination in the
# matrix, you can use a line such as:
#     addons: {apt: {packages: [libfcgi-dev,libgmp-dev]}}
#
# fast_finish: build successful when every builds not in allow_failure are finished
# i.e. not waiting any of the allow_failure to finish
matrix:
  include:
  # We grab the appropriate GHC and cabal-install versions from hvr's PPA. See:
  # https://github.com/hvr/multi-ghc-travis
  - env: BUILD=cabal GHCVER=7.10.3 CABALVER=1.24
    compiler: ": #GHC 7.10.3"
    addons: {apt: {packages: [cabal-install-1.24,ghc-7.10.3,happy-1.19.5], sources: [hvr-ghc]}}
  - env: BUILD=cabal GHCVER=8.0.2 CABALVER=1.24
    compiler: ": #GHC 8.0.2"
    addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.2,happy-1.19.5], sources: [hvr-ghc]}}
  - env: BUILD=cabal GHCVER=8.2.2 CABALVER=2.0
    compiler: ": #GHC 8.2.2"
    addons: {apt: {packages: [cabal-install-2.0,ghc-8.2.2,happy-1.19.5], sources: [hvr-ghc]}}
  - env: BUILD=cabal GHCVER=8.4.3 CABALVER=2.2
    compiler: ": #GHC 8.4.3"
    addons: {apt: {packages: [cabal-install-2.2,ghc-8.4.3,happy-1.19.5], sources: [hvr-ghc]}}
  - env: BUILD=cabal GHCVER=8.6.3 CABALVER=2.4
    compiler: ": #GHC 8.6.3"
    addons: {apt: {packages: [cabal-install-2.4,ghc-8.6.3,happy-1.19.5], sources: [hvr-ghc]}}


  # Build with the newest GHC and cabal-install. This is an accepted failure,
  # see below.
  # - env: BUILD=cabal GHCVER=head  CABALVER=head
  #   compiler: ": #GHC HEAD"
  #   addons: {apt: {packages: [cabal-install-head,ghc-head,happy-1.19.5], sources: [hvr-ghc]}}

  # The Stack builds. We can pass in arbitrary Stack arguments via the ARGS
  # variable, such as using --stack-yaml to point to a different file.
  - env: BUILD=stack ARGS="--resolver lts-12"
    compiler: ": #stack 8.4.3"
    addons: {apt: {packages: [ghc-8.4.3], sources: [hvr-ghc]}}
  - env: BUILD=stack ARGS="--resolver lts-13"
    compiler: ": #stack 8.6.3"
    addons: {apt: {packages: [ghc-8.6.3], sources: [hvr-ghc]}}

  # - env: BUILD=stack ARGS="--resolver lts-8 --library-profiling --executable-profiling"
  #   compiler: ": #stack 8.0.2"
  #   addons: {apt: {packages: [ghc-8.0.2], sources: [hvr-ghc]}}

  # Nightly builds are allowed to fail
  #- env: BUILD=stack ARGS="--resolver nightly"
  #  compiler: ": #stack nightly"
  #  addons: {apt: {packages: [libgmp-dev]}}

  # - env: BUILD=stack ARGS="--resolver lts-7"
  # - compiler: ": #stack 8.0.1 osx"
  # - os: osx

  # - env: BUILD=stack ARGS="--resolver nightly"
  #   compiler: ": #stack nightly osx"
  #   os: osx

  allow_failures:
  - env: BUILD=cabal GHCVER=head  CABALVER=head
  - env: BUILD=stack ARGS="--resolver nightly"

  fast_finish: true

before_install:
# Using compiler above sets CC to an invalid value, so unset it
- unset CC

# We want to always allow newer versions of packages when building on GHC HEAD
- CABALARGS=""
- OPTS="-O0 -Wall -fno-warn-unused-do-bind -fno-warn-unused-imports -Werror"
- if [ "x$GHCVER" = "xhead" ]; then CABALARGS=--allow-newer; fi

- export PATH=/opt/happy/1.19.5/bin/:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.local/bin:$HOME/.cabal/bin:$PATH
- mkdir -p ~/.local/bin

# Download and unpack the stack executable
- |
  if [ `uname` = "Darwin" ]
  then
    curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
  else
    curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  fi

script:
- |
  case "$BUILD" in
    stack)
      ulimit -n 4096
      stack --no-terminal $ARGS install --fast --flag 'aeson:fast' --flag 'skylighting-core:executable' --ghc-options="$OPTS" skylighting-core && \
      cd skylighting && \
      skylighting-extract ../skylighting-core/xml/*.xml && \
      cd .. && \
      stack test --no-terminal $ARGS --haddock --no-haddock-deps --fast --flag 'aeson:fast' --flag 'skylighting:executable' --ghc-options="$OPTS"
      ;;
    cabal)
      cabal update && \
      cd skylighting-core && \
      cabal install --only-dependencies --force-reinstalls -v2 -ffast -fexecutable --disable-optimization --enable-tests && \
      cabal install -v2 -ffast -fexecutable --force-reinstalls --disable-optimization --enable-tests --run-tests --ghc-options="$OPTS" && \
      cd ../skylighting && \
      skylighting-extract ../skylighting-core/xml/*.xml && \
      cabal configure -v2 -ffast -fexecutable --disable-optimization --enable-tests --ghc-options="$OPTS" && \
      cabal sdist --output-directory=sourcedist && \
      cd sourcedist && \
      cabal install --force-reinstalls -v2 -ffast -fexecutable --disable-optimization --enable-tests --run-tests --ghc-options="$OPTS"
      ;;
  esac
